site_name: oikos
site_description: Librería de Python para modelos y análisis económico
site_author: Marcos Junior
repo_url: https://github.com/marcosjuniorhernandez/economy
repo_name: economy

theme:
  name: material
  language: es
  # Logo de Manim style: Usa una letra M o el nombre de tu lib
  icon:
    logo: material/chart-timeline-variant 
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.sections # Esto crea las líneas divisorias estilo Manim
    - navigation.expand   # Mantiene el menú desplegado como en la imagen
    - navigation.indexes
    - content.code.copy
    - content.tabs.link
    - navigation.top
  palette:
    # Paleta de colores exacta de Manim (Blanco puro y Gris/Indigo)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo claro

# Esto separa las secciones con títulos en negrita en el lateral
nav:
  - Instalación: 
    - index.md
  - Tutoriales & Guías:
    - Manual de uso: manual.md
    - Manual de visualización: manual2.md
  - Referencia:
    - Registro de cambios: changelog.md
    - Contribuyendo: contributing.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js